INSERT INTO countries (code, name, flag_emoji, is_active) VALUES
  ('AF', 'Afghanistan', '🇦🇫', true),
  ('AL', 'Albania', '🇦🇱', true),
  ('DZ', 'Algeria', '🇩🇿', true),
  ('AS', 'American Samoa', '🇦🇸', true),
  ('AD', 'Andorra', '🇦🇩', true),
  ('AO', 'Angola', '🇦🇴', true),
  ('AI', 'Anguilla', '🇦🇮', true),
  ('AQ', 'Antarctica', '🇦🇶', true),
  ('AG', 'Antigua and Barbuda', '🇦🇬', true),
  ('AR', 'Argentina', '🇦🇷', true),
  ('AM', 'Armenia', '🇦🇲', true),
  ('AW', 'Aruba', '🇦🇼', true),
  ('AU', 'Australia', '🇦🇺', true),
  ('AT', 'Austria', '🇦🇹', true),
  ('AZ', 'Azerbaijan', '🇦🇿', true),
  ('BS', 'Bahamas', '🇧🇸', true),
  ('BH', 'Bahrain', '🇧🇭', true),
  ('BD', 'Bangladesh', '🇧🇩', true),
  ('BB', 'Barbados', '🇧🇧', true),
  ('BY', 'Belarus', '🇧🇾', true),
  ('BE', 'Belgium', '🇧🇪', true),
  ('BZ', 'Belize', '🇧🇿', true),
  ('BJ', 'Benin', '🇧🇯', true),
  ('BM', 'Bermuda', '🇧🇲', true),
  ('BT', 'Bhutan', '🇧🇹', true),
  ('BO', 'Bolivia', '🇧🇴', true),
  ('BA', 'Bosnia and Herzegovina', '🇧🇦', true),
  ('BW', 'Botswana', '🇧🇼', true),
  ('BV', 'Bouvet Island', '🇧🇻', true),
  ('BR', 'Brazil', '🇧🇷', true),
  ('IO', 'British Indian Ocean Territory', '🇮🇴', true),
  ('VG', 'British Virgin Islands', '🇻🇬', true),
  ('BN', 'Brunei', '🇧🇳', true),
  ('BG', 'Bulgaria', '🇧🇬', true),
  ('BF', 'Burkina Faso', '🇧🇫', true),
  ('BI', 'Burundi', '🇧🇮', true),
  ('KH', 'Cambodia', '🇰🇭', true),
  ('CM', 'Cameroon', '🇨🇲', true),
  ('CA', 'Canada', '🇨🇦', true),
  ('CV', 'Cape Verde', '🇨🇻', true),
  ('BQ', 'Caribbean Netherlands', '🇧🇶', true),
  ('KY', 'Cayman Islands', '🇰🇾', true),
  ('CF', 'Central African Republic', '🇨🇫', true),
  ('TD', 'Chad', '🇹🇩', true),
  ('CL', 'Chile', '🇨🇱', true),
  ('CN', 'China', '🇨🇳', true),
  ('CX', 'Christmas Island', '🇨🇽', true),
  ('CC', 'Cocos (Keeling) Islands', '🇨🇨', true),
  ('CO', 'Colombia', '🇨🇴', true),
  ('KM', 'Comoros', '🇰🇲', true),
  ('CK', 'Cook Islands', '🇨🇰', true),
  ('CR', 'Costa Rica', '🇨🇷', true),
  ('HR', 'Croatia', '🇭🇷', true),
  ('CU', 'Cuba', '🇨🇺', true),
  ('CW', 'Curaçao', '🇨🇼', true),
  ('CY', 'Cyprus', '🇨🇾', true),
  ('CZ', 'Czechia', '🇨🇿', true),
  ('CD', 'DR Congo', '🇨🇩', true),
  ('DK', 'Denmark', '🇩🇰', true),
  ('DJ', 'Djibouti', '🇩🇯', true),
  ('DM', 'Dominica', '🇩🇲', true),
  ('DO', 'Dominican Republic', '🇩🇴', true),
  ('EC', 'Ecuador', '🇪🇨', true),
  ('EG', 'Egypt', '🇪🇬', true),
  ('SV', 'El Salvador', '🇸🇻', true),
  ('GQ', 'Equatorial Guinea', '🇬🇶', true),
  ('ER', 'Eritrea', '🇪🇷', true),
  ('EE', 'Estonia', '🇪🇪', true),
  ('SZ', 'Eswatini', '🇸🇿', true),
  ('ET', 'Ethiopia', '🇪🇹', true),
  ('FK', 'Falkland Islands', '🇫🇰', true),
  ('FO', 'Faroe Islands', '🇫🇴', true),
  ('FJ', 'Fiji', '🇫🇯', true),
  ('FI', 'Finland', '🇫🇮', true),
  ('FR', 'France', '🇫🇷', true),
  ('GF', 'French Guiana', '🇬🇫', true),
  ('PF', 'French Polynesia', '🇵🇫', true),
  ('TF', 'French Southern and Antarctic Lands', '🇹🇫', true),
  ('GA', 'Gabon', '🇬🇦', true),
  ('GM', 'Gambia', '🇬🇲', true),
  ('GE', 'Georgia', '🇬🇪', true),
  ('DE', 'Germany', '🇩🇪', true),
  ('GH', 'Ghana', '🇬🇭', true),
  ('GI', 'Gibraltar', '🇬🇮', true),
  ('GR', 'Greece', '🇬🇷', true),
  ('GL', 'Greenland', '🇬🇱', true),
  ('GD', 'Grenada', '🇬🇩', true),
  ('GP', 'Guadeloupe', '🇬🇵', true),
  ('GU', 'Guam', '🇬🇺', true),
  ('GT', 'Guatemala', '🇬🇹', true),
  ('GG', 'Guernsey', '🇬🇬', true),
  ('GN', 'Guinea', '🇬🇳', true),
  ('GW', 'Guinea-Bissau', '🇬🇼', true),
  ('GY', 'Guyana', '🇬🇾', true),
  ('HT', 'Haiti', '🇭🇹', true),
  ('HM', 'Heard Island and McDonald Islands', '🇭🇲', true),
  ('HN', 'Honduras', '🇭🇳', true),
  ('HK', 'Hong Kong', '🇭🇰', true),
  ('HU', 'Hungary', '🇭🇺', true),
  ('IS', 'Iceland', '🇮🇸', true),
  ('IN', 'India', '🇮🇳', true),
  ('ID', 'Indonesia', '🇮🇩', true),
  ('IR', 'Iran', '🇮🇷', true),
  ('IQ', 'Iraq', '🇮🇶', true),
  ('IE', 'Ireland', '🇮🇪', true),
  ('IM', 'Isle of Man', '🇮🇲', true),
  ('IL', 'Israel', '🇮🇱', true),
  ('IT', 'Italy', '🇮🇹', true),
  ('CI', 'Ivory Coast', '🇨🇮', true),
  ('JM', 'Jamaica', '🇯🇲', true),
  ('JP', 'Japan', '🇯🇵', true),
  ('JE', 'Jersey', '🇯🇪', true),
  ('JO', 'Jordan', '🇯🇴', true),
  ('KZ', 'Kazakhstan', '🇰🇿', true),
  ('KE', 'Kenya', '🇰🇪', true),
  ('KI', 'Kiribati', '🇰🇮', true),
  ('XK', 'Kosovo', '🇽🇰', true),
  ('KW', 'Kuwait', '🇰🇼', true),
  ('KG', 'Kyrgyzstan', '🇰🇬', true),
  ('LA', 'Laos', '🇱🇦', true),
  ('LV', 'Latvia', '🇱🇻', true),
  ('LB', 'Lebanon', '🇱🇧', true),
  ('LS', 'Lesotho', '🇱🇸', true),
  ('LR', 'Liberia', '🇱🇷', true),
  ('LY', 'Libya', '🇱🇾', true),
  ('LI', 'Liechtenstein', '🇱🇮', true),
  ('LT', 'Lithuania', '🇱🇹', true),
  ('LU', 'Luxembourg', '🇱🇺', true),
  ('MO', 'Macau', '🇲🇴', true),
  ('MG', 'Madagascar', '🇲🇬', true),
  ('MW', 'Malawi', '🇲🇼', true),
  ('MY', 'Malaysia', '🇲🇾', true),
  ('MV', 'Maldives', '🇲🇻', true),
  ('ML', 'Mali', '🇲🇱', true),
  ('MT', 'Malta', '🇲🇹', true),
  ('MH', 'Marshall Islands', '🇲🇭', true),
  ('MQ', 'Martinique', '🇲🇶', true),
  ('MR', 'Mauritania', '🇲🇷', true),
  ('MU', 'Mauritius', '🇲🇺', true),
  ('YT', 'Mayotte', '🇾🇹', true),
  ('MX', 'Mexico', '🇲🇽', true),
  ('FM', 'Micronesia', '🇫🇲', true),
  ('MD', 'Moldova', '🇲🇩', true),
  ('MC', 'Monaco', '🇲🇨', true),
  ('MN', 'Mongolia', '🇲🇳', true),
  ('ME', 'Montenegro', '🇲🇪', true),
  ('MS', 'Montserrat', '🇲🇸', true),
  ('MA', 'Morocco', '🇲🇦', true),
  ('MZ', 'Mozambique', '🇲🇿', true),
  ('MM', 'Myanmar', '🇲🇲', true),
  ('NA', 'Namibia', '🇳🇦', true),
  ('NR', 'Nauru', '🇳🇷', true),
  ('NP', 'Nepal', '🇳🇵', true),
  ('NL', 'Netherlands', '🇳🇱', true),
  ('NC', 'New Caledonia', '🇳🇨', true),
  ('NZ', 'New Zealand', '🇳🇿', true),
  ('NI', 'Nicaragua', '🇳🇮', true),
  ('NE', 'Niger', '🇳🇪', true),
  ('NG', 'Nigeria', '🇳🇬', true),
  ('NU', 'Niue', '🇳🇺', true),
  ('NF', 'Norfolk Island', '🇳🇫', true),
  ('KP', 'North Korea', '🇰🇵', true),
  ('MK', 'North Macedonia', '🇲🇰', true),
  ('MP', 'Northern Mariana Islands', '🇲🇵', true),
  ('NO', 'Norway', '🇳🇴', true),
  ('OM', 'Oman', '🇴🇲', true),
  ('PK', 'Pakistan', '🇵🇰', true),
  ('PW', 'Palau', '🇵🇼', true),
  ('PS', 'Palestine', '🇵🇸', true),
  ('PA', 'Panama', '🇵🇦', true),
  ('PG', 'Papua New Guinea', '🇵🇬', true),
  ('PY', 'Paraguay', '🇵🇾', true),
  ('PE', 'Peru', '🇵🇪', true),
  ('PH', 'Philippines', '🇵🇭', true),
  ('PN', 'Pitcairn Islands', '🇵🇳', true),
  ('PL', 'Poland', '🇵🇱', true),
  ('PT', 'Portugal', '🇵🇹', true),
  ('PR', 'Puerto Rico', '🇵🇷', true),
  ('QA', 'Qatar', '🇶🇦', true),
  ('CG', 'Republic of the Congo', '🇨🇬', true),
  ('RO', 'Romania', '🇷🇴', true),
  ('RU', 'Russia', '🇷🇺', true),
  ('RW', 'Rwanda', '🇷🇼', true),
  ('RE', 'Réunion', '🇷🇪', true),
  ('BL', 'Saint Barthélemy', '🇧🇱', true),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', '🇸🇭', true),
  ('KN', 'Saint Kitts and Nevis', '🇰🇳', true),
  ('LC', 'Saint Lucia', '🇱🇨', true),
  ('MF', 'Saint Martin', '🇲🇫', true),
  ('PM', 'Saint Pierre and Miquelon', '🇵🇲', true),
  ('VC', 'Saint Vincent and the Grenadines', '🇻🇨', true),
  ('WS', 'Samoa', '🇼🇸', true),
  ('SM', 'San Marino', '🇸🇲', true),
  ('SA', 'Saudi Arabia', '🇸🇦', true),
  ('SN', 'Senegal', '🇸🇳', true),
  ('RS', 'Serbia', '🇷🇸', true),
  ('SC', 'Seychelles', '🇸🇨', true),
  ('SL', 'Sierra Leone', '🇸🇱', true),
  ('SG', 'Singapore', '🇸🇬', true),
  ('SX', 'Sint Maarten', '🇸🇽', true),
  ('SK', 'Slovakia', '🇸🇰', true),
  ('SI', 'Slovenia', '🇸🇮', true),
  ('SB', 'Solomon Islands', '🇸🇧', true),
  ('SO', 'Somalia', '🇸🇴', true),
  ('ZA', 'South Africa', '🇿🇦', true),
  ('GS', 'South Georgia', '🇬🇸', true),
  ('KR', 'South Korea', '🇰🇷', true),
  ('SS', 'South Sudan', '🇸🇸', true),
  ('ES', 'Spain', '🇪🇸', true),
  ('LK', 'Sri Lanka', '🇱🇰', true),
  ('SD', 'Sudan', '🇸🇩', true),
  ('SR', 'Suriname', '🇸🇷', true),
  ('SJ', 'Svalbard and Jan Mayen', '🇸🇯', true),
  ('SE', 'Sweden', '🇸🇪', true),
  ('CH', 'Switzerland', '🇨🇭', true),
  ('SY', 'Syria', '🇸🇾', true),
  ('ST', 'São Tomé and Príncipe', '🇸🇹', true),
  ('TW', 'Taiwan', '🇹🇼', true),
  ('TJ', 'Tajikistan', '🇹🇯', true),
  ('TZ', 'Tanzania', '🇹🇿', true),
  ('TH', 'Thailand', '🇹🇭', true),
  ('TL', 'Timor-Leste', '🇹🇱', true),
  ('TG', 'Togo', '🇹🇬', true),
  ('TK', 'Tokelau', '🇹🇰', true),
  ('TO', 'Tonga', '🇹🇴', true),
  ('TT', 'Trinidad and Tobago', '🇹🇹', true),
  ('TN', 'Tunisia', '🇹🇳', true),
  ('TR', 'Turkey', '🇹🇷', true),
  ('TM', 'Turkmenistan', '🇹🇲', true),
  ('TC', 'Turks and Caicos Islands', '🇹🇨', true),
  ('TV', 'Tuvalu', '🇹🇻', true),
  ('UG', 'Uganda', '🇺🇬', true),
  ('UA', 'Ukraine', '🇺🇦', true),
  ('AE', 'United Arab Emirates', '🇦🇪', true),
  ('GB', 'United Kingdom', '🇬🇧', true),
  ('US', 'United States', '🇺🇸', true),
  ('UM', 'United States Minor Outlying Islands', '🇺🇲', true),
  ('VI', 'United States Virgin Islands', '🇻🇮', true),
  ('UY', 'Uruguay', '🇺🇾', true),
  ('UZ', 'Uzbekistan', '🇺🇿', true),
  ('VU', 'Vanuatu', '🇻🇺', true),
  ('VA', 'Vatican City', '🇻🇦', true),
  ('VE', 'Venezuela', '🇻🇪', true),
  ('VN', 'Vietnam', '🇻🇳', true),
  ('WF', 'Wallis and Futuna', '🇼🇫', true),
  ('EH', 'Western Sahara', '🇪🇭', true),
  ('YE', 'Yemen', '🇾🇪', true),
  ('ZM', 'Zambia', '🇿🇲', true),
  ('ZW', 'Zimbabwe', '🇿🇼', true),
  ('AX', 'Åland Islands', '🇦🇽', true);
